### ISSUE TITLE
Apple Match-O Linker Error

### ISSUE THREAD

**Issue by ghost** [meiwin/NgKeyboardTracker#3] opened 2015-09-08 04:02 UTC
Hello!

I am getting the following error after I put the code in the AppDelegate.m file:

ld: warning: directory not found for option '-L/Users/seung/Desktop/Websites/FirstApp/build/Debug-iphoneos'
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_NgKeyboardTracker", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any help would be appreciated. Thank you!

**Comment by ghost** [comment] 2015-09-08 04:03
This happened when I put the below code in to my AppDelegate:
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[NgKeyboardTracker sharedTracker] start]; // start tracking
  return YES;
  }
- (void)applicationWillTerminate:(UIApplication *)application {
  // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
  [[NgKeyboardTracker sharedTracker] stop]; // stop tracking
  }

**Comment by meiwin** [comment] 2015-09-08 12:54
How do you include NgKeyboardTracker in your project, Cocoapods or manual copy?

If manual copy, make sure you've included NgKeyboardTracker.m in your target.

**Comment by ghost** [comment] 2015-09-08 13:34
Thanks for your quick response. i'm using the Podfile. Also, is this framework a InputBar with textfield that I can use for my app? I am trying to implement a CommentsDetailsView controller and I was wondering if this was the right framework to use.. Thanks!

**Comment by meiwin** [comment] 2015-09-08 13:48
If you're using cocoapods, make sure that you open <YourProject>.xcworkspace.
From your error, it seems very likely that you opened and compiled from <YourProject>.xcodeproj 

This project does not include input bar, there're many open-source input bar you can try out there, I do not have any recommendation.

**Comment by meiwin** [comment] 2015-09-09 01:37
I am closing the issue because it seems to be caused by Xcode project configuration.

**Closed as completed by meiwin** 2015-09-09 01:37 UTC
